//
// Created by archie on 4/19/17.
//

#ifndef BIN_EVO_PROJEKT_PARAMS_H
#define BIN_EVO_PROJEKT_PARAMS_H

#endif //BIN_EVO_PROJEKT_PARAMS_H


#define MUTATIONPROB 100
#define MUTATEDGENES 4
#define CROSSOVERPROBABILITY 20
#define TOURNAMENTSIZE 7
#define POPSIZE 20
#define MAXGENERATIONS 500
#define STATES 8
#define NEIGHBOURHOOD 9
#define SIMULATIONSTEPS 25
#define SIZEOFCA 51
#define MINRULES 10
#define MAXRULES 20// = 4 * 9
#define FILENAME 20