//
// Created by archie on 4/19/17.
//

#ifndef BIN_EVO_PROJEKT_PARAMS_H
#define BIN_EVO_PROJEKT_PARAMS_H

#endif //BIN_EVO_PROJEKT_PARAMS_H


#define MUTATIONPROB 100
#define MUTATEDGENES 4
#define CROSSOVERPROBABILITY 0
#define TOURNAMENTSIZE 7
#define POPSIZE 20
#define MAXGENERATIONS 300
#define STATES 8
#define NEIGHBOURHOOD 9;
#define SIMULATIONSTEPS 10
#define SIZEOFCA 21
#define MINRULES 10
#define MAXRULES 15// = 4 * 9